name: Release
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Public binaries
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Build binaries
        run: |
          make release
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: release/network-microburst-*
        asset_name: release
        tag: ${{ github.ref }}
        overwrite: true
        body: "test release"
